### ISSUE TITLE
Argument 3 passed to JsonRPC\Client::__construct() must be an instance of JsonRPC\HttpClient, array given

### ISSUE THREAD

**Issue by tamer-hassan** [macedd/laravelrpc#5]
ErrorException in Client.php line 66: Argument 3 passed to JsonRPC\Client::__construct() must be an instance of JsonRPC\HttpClient, array given, called in /var/www/myapp/vendor/thiagof/laravelrpc/src/RpcClientWrapper.php on line 54 and defined

**Comment by macedd** [comment]
Thats due to JsonRPC Version upgrade.
Fixing it on https://github.com/thiagof/laravelrpc/tree/tf-rpc-version

Could you help on testing?
