### ISSUE TITLE
Doesn't work in Laravel 5.3

### ISSUE THREAD

**Issue by MysticD2** [macedd/laravelrpc#8]
I cannot get this package to install in laravel 5.3 with composer. I get the following error:

composer require thiagof/laravelrpc
Using version ^0.1.4 for thiagof/laravelrpc
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for thiagof/laravelrpc ^0.1.4 -> satisfiable by thiagof/laravelrpc[0.1.4].
    - Conclusion: remove laravel/framework v5.3.18
    - Conclusion: don't install laravel/framework v5.3.18
    - thiagof/laravelrpc 0.1.4 requires illuminate/support >=5.0,<5.2 -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.41|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.3.18
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.3.18
    - Installation request for laravel/framework (locked at v5.3.18, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.18].

Installation failed, reverting ./composer.json to its original content.

**Comment by macedd** [comment]
Yes upgraded the package to laravel latest version
Please check out again
